Controllers/FavoriteFruitController.cs
using Microsoft.AspNetCore.Mvc;
using Pearmageddon.Models;

namespace Pearmageddon.Controllers
{
    [Route("[controller]")]
    [ApiExplorerSettings(IgnoreApi = true)]

    public class FavoriteFruitController : Controller
    {
        [Route("Survey")]
        [HttpGet]
        public IActionResult Survey()
        {
            return View(GetFruitModels());
        }
        [Route("Survey")]
        [HttpPost]
        public IActionResult Survey(List<FruitModel> fruitModels)
        {
            if (!ModelState.IsValid)
            {
                return View(fruitModels);
            }
            return RedirectToAction("Index", "Home");
        }
        private IEnumerable<FruitModel> GetFruitModels()
        {
            return new List<FruitModel>
            {
                new AppleModel { ID = 1, Name = "Apple", Variety = "" },
                new FruitModel { ID = 2, Name = "Banana", Variety = "" },
                new FruitModel { ID = 3, Name = "Cherry", Variety = "" },
                new FruitModel { ID = 4, Name = "Date", Variety = "" }
            };
        }
    }
}

Views/FavoriteFruit/Survey.cshtml
@model List<FruitModel>

<form asp-action="Survey" asp-controller="FavoriteFruit">
    @for (int i = 0; i < Model.Count(); i++)
    {
        @if(Model[i] is AppleModel)
        {
            <partial name="_AppleFruit" for="@Model[i]" />
        }
        else
        {
            <partial name="_Fruit" for="@Model[i]" />
        }

    }
    <button type="submit">Submit Survey</button>
</form>